export const END_POINTS = {
  HOME_MEMES: "/template-library/home-page-memes",
  HOME_BANNERS: "/template-library/home-page-banners",
  HOME_WALLPAPERS: "/template-library/home-page-wallpapers",
  HOME_SPARKY: "/sticker-library/home-page-others",
  HOME_VOID: "/sticker-library/home-page-void",
  HOME_TRUMP: "/sticker-library/home-page-trump",
  HOME_BILLY_CAT: "/sticker-library/home-page-stickers",
  MEMES: "/template-library/memes",
  BANNERS: "/template-library/banners",
  WALLPAPERS: "/template-library/wallpapers",
  SPARKY: "/sticker-library/others",
  VOID: "/sticker-library/void",
  TRUMP: "/sticker-library/trump",
  BILLY_CAT: "/sticker-library/stickers",
  GET_ONE_TEMPLATE: (id: number) => `/template-library/${id}`,
};
